version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-9b1jb0ftc4km --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml