AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app-hello-world

  Sample SAM Template for sam-app-hello-world

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: my-app-hello-world
    Description: hello world
    Author: wesley
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-9b1jb0ftc4km/63297f9c0f3f8e8a504c58cbb085028e
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-9b1jb0ftc4km/fcf7be61b7c96d9745d0deacf19b26d4
    Labels:
    - tests
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/user1/my-app-project
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-9b1jb0ftc4km/166add05420216f5b2123cabefbc6395
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
